# Generated by Django 3.0.5 on 2020-04-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraset',
            name='camera_main',
            field=models.BooleanField(blank=True),
        ),
    ]
