# Generated by Django 3.0.5 on 2020-05-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20200503_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='product_job',
            new_name='product_jobno',
        ),
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='product_transaction',
            new_name='product_oum',
        ),
        migrations.RenameField(
            model_name='inventoryproduct',
            old_name='product_unit',
            new_name='product_remarks',
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_company',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_currency',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_febexcrate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_invdate',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_invoice',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_ponumbers',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_pricefrom',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_qty',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_totalprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='product_ttvpn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='product_location',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
