# Generated by Django 3.0.5 on 2020-06-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_remove_inventoryproduct_product_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameraset',
            old_name='test',
            new_name='camera_slave',
        ),
        migrations.RemoveField(
            model_name='cameraset',
            name='camera_image',
        ),
        migrations.AlterField(
            model_name='cameraset',
            name='camera_main',
            field=models.CharField(blank=True, default=0, max_length=200),
            preserve_default=False,
        ),
    ]
