# Generated by Django 3.0.5 on 2020-06-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_auto_20200624_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='product_currency',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
