# Generated by Django 3.0.5 on 2020-06-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_auto_20200624_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryproduct',
            name='product_febexcrate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='product_totalprice',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
