# Generated by Django 3.0.5 on 2020-06-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_auto_20200624_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttvproject',
            name='p_desc',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
