# Generated by Django 3.0.5 on 2020-06-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_ttvproject_p_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameraset',
            name='camera_cells',
        ),
        migrations.RemoveField(
            model_name='cameraset',
            name='camera_project',
        ),
        migrations.AddField(
            model_name='cameraset',
            name='camera_cell_tag',
            field=models.ManyToManyField(to='production.Ttvcell'),
        ),
    ]
